// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/goals/new": {
    params: {};
  };
  "/goals/:goalId": {
    params: {
      "goalId": string;
    };
  };
  "/goals/:goalId/edit": {
    params: {
      "goalId": string;
    };
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/goals/new" | "/goals/:goalId" | "/goals/:goalId/edit" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/goals.new.tsx": {
    id: "routes/goals.new";
    page: "/goals/new";
  };
  "routes/goals.$goalId.tsx": {
    id: "routes/goals.$goalId";
    page: "/goals/:goalId";
  };
  "routes/goals.$goalId.edit.tsx": {
    id: "routes/goals.$goalId.edit";
    page: "/goals/:goalId/edit";
  };
  "routes/devtools-silent.tsx": {
    id: "routes/devtools-silent";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
};